name: GHA Composite WF Example 1 - V4

run-name:  "#${{ github.run_number }}. Build and Deploy v2 on ${{ github.ref_type }} '${{ github.ref_name }}'. Triggered by: ${{ github.triggering_actor }}"

on:
  # Allow for manual execution and to trigger Secondary region deployments
  workflow_dispatch:
    inputs:
      DeployToUatSecondary:
        description: 'Deploy into UAT Secondary region?'
        required: false
        default: false
      DeployToPrdSecondary:
        description: 'Deploy into Prd Secondary region?'
        required: false
        default: false
      BypassCodeScan:
        description: 'Bypass code scan?'
        required: false
        default: false
        
  # Auto trigger when pushes to selected branch naming conventions occur
  push: 
    branches: [main, feat/**, feature/**, release/**]
    paths-ignore: ['*.md']
  # Auto trigger when a release is created
  release:
    types: [published]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "running docker build --target=build"
      - name: Test
        run: echo "running docker build --target=test"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Lint Tool
        run: echo "Setting up Lint tool"
      - name: Lint Code
        run: echo "Linting code"

  code-scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.BypassCodeScan != true }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Vericode
        run: echo "downloading Vericode"
      - name: Scan
        run: echo "scanning code"

  publish:
    runs-on: ubuntu-latest
    if: ${{ always() && (github.event.inputs.BypassCodeScan == true || needs.code-scan.result == 'success') }}
    needs: [build-and-test, code-scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: echo "running docker build --target=final"
      - name: Download Trivy
        run: echo "downloading Trivy"
      - name: Aqua Image Scan
        run: echo "scanning image"
      - name: Login to ACR
        run: echo "logging into ACR"
      - name: Publish Image
        run: echo "publishing image with tag ???"
      - name: Logout of ACR
        run: echo "logging out of ACR"

  deploy-to-dev:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [publish]
    environment: dev
    steps:
      - name: Deploy to Dev
        run: echo "deploying via helm"
      - name: Capture dependencies
        env:
          NEEDS: ${{ toJSON(needs) }}     
        run: |
          echo "$NEEDS"

  deploy-to-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.DeployToUatSecondary != true || github.event.inputs.DeployToPrdSecondary != true }}
    needs: [publish]
    environment: test
    steps:
      - name: Deploy to Test
        run: echo "deploying via helm"

  deploy-to-uat-primary:
    # only runnable if deploying a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.inputs.DeployToUatSecondary == false }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-test]
    environment: uat
    steps:
      - name: Deploy to UAT Primary
        run: echo "deploying via helm"

  # Thinking here:
  # Usually deployment into UAT Secondary would only be allowed on a release which has already gone into UAT Primary previously.
  # But, If a fix is required to DR enacted for an extended period then the Primary pre-req might not be viable.
  # Equally if it's a new build during DR then it cannot possibly be deployed into Dev/Test...
  # Alas chaining this off just Publish
  # Main issue here... cannot manually mark a pre-req Job as successful in GH
  deploy-to-uat-secondary:
    # only runnable if deploying a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.inputs.DeployToUatSecondary == true }}
    runs-on: ubuntu-latest
    needs: [publish]
    environment: uat
    steps:
      - name: Deploy to UAT Secondary
        run: echo "deploying via helm"

  deploy-to-prd-primary:
    # only runnable if deploying a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.inputs.DeployToPrdSecondary == false }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-uat-primary]
    environment: prd
    steps:
      - name: Deploy to PRD Primary
        run: echo "deploying via helm"
        
  deploy-to-prd-secondary:
    # only runnable if deploying a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.inputs.DeployToPrdSecondary == true }}
    runs-on: ubuntu-latest
    needs: [publish]
    environment: prd
    steps:
      - name: Deploy to PRD Secondary
        run: echo "deploying via helm"
      - name: Capture dependencies
        env:
          NEEDS: ${{ toJSON(needs) }}     
        run: |
          echo "$NEEDS"
